spring.application.name=demo-devops
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.profiles.active=docker
springdoc.api-docs.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true 
management.prometheus.metrics.export.enabled=true